ocelot-collab/ocelot

.gitignore, ocelot/cpbd/csr.py, ocelot/cpbd/optics.py
Hi everyone,
I have been working for some time on a few changes which can significantly speed-up particle tracking (with transfer maps) and the calculation of CSR effects. Many of these changes come directly from my own small tracking code [`Wake-T`](https://github.com/AngelFP/Wake-T) for plasma accelerators, in which the transfer maps and CSR are anyways based on the `Ocelot` implementation.
The changes are only in the `optics.py` and `csr.py` files and can be summarized as follows:
* `optics.py` 
* The `numpy_apply` method has been greatly simplified to a single line using 'np.einsum'. It now performs full matrix multiplication and is also ~20-30% faster than before.
* The `numexpr_apply` method has also been modified in order not to require making a copy of the initial beam matrix and …
=> Performance improvements in tracking and CSR

unit_tests/pytest.ini
pytest 6.0.1 throws a PytestUnknownMarkWarning because the marker "update" isn't described in pytest.ini.
=> Fix for PytestUnknownMarkWarning

ocelot/cpbd/beam.py, ocelot/cpbd/optics.py
Python 3.8 compiler now produces a SyntaxWarning when identity checks (is and is not) are used with certain types of literals (e.g. strings, numbers).
=> Fix SyntaxWarning: is with a literal

ocelot/cpbd/beam.py, ocelot/cpbd/physics_proc.py, unit_tests/utils_test/particle_array_test.py
Add new attribute to LostParticleRecorder to record at which position s how many particles get lost.
Additionally the function "delete_indices" was renamed to "delete_particles" and  rm_particle() prints a warning that the function is deprecated.
=> add record of positon to number of lost particles to LostParticleRecorder

demos/ipython_tutorials/5_CSR.ipynb, ocelot/cpbd/csr.py
Something simple and easy for my first pull request.  Example:
```
x = X()
x.foo = 3
x.bar = "baz"
```
This is an anti-pattern.  Initialisation should go in the initialiser.  So I fixed this for the class CSR and also the jupyter notebook where it is used. 
change is backwards compatible / doesn't break api.
=> CSR init with **kwarg + updated ipynb notebook (my first pull request)

ocelot/adaptors/pmd.py, ocelot/cpbd/beam.py, ocelot/cpbd/io.py, setup.py, unit_tests/adaptors_test/test_pmd.py
Converters `ParticleArray` to and from `ParticleGroup` with tests.  added .h5 extension to `load_particle_array` / `load_particle_array` in `io.py`, but without any tests as it had no tests already.
Also cheekily added some properties to the ParticleArray class for common derived quantities: pz, p0, energies and momenta so these calculations don't need to be done everywhere.
I didn't edit the setup.py because openpmd_beamphysics isn't on pip.  Could add [the git repo link directly](https://stackoverflow.com/questions/32688688/how-to-write-setup-py-to-include-a-git-repository-as-a-dependency/54794506#54794506) to the setup.py but I don't know what the implications of this are.
=> Openpmd beamphysics support

ocelot/cpbd/beam.py, unit_tests/cpbd/test_beam.py
I wrote some code for generating a Gaussian beam from Twiss parameters and covariance matrices a while back.  Now I am sending a pull request.  From Twiss parameters to covariance matrices, and from covariance matrices to Twiss parameters.  I used generate_parray in beam.py before writing this back in the day but I found the parametrisation personally not very useful (no emittance) and the default values didn't make any sense to me resulting in mistakes being made on my part.  So this is something else that can be used to generate Gaussian beams with all the correct correlations.  + a test.
=> Gaussian beam generation based on covariance matrices and Twiss parameters

ocelot/cpbd/beam.py
add missing emit_xn and emit_yn attributes to the Twiss instance returned by get_envelope and also fixed Twiss as a default argument.  It's not a good idea to have mutable instances as kwargs in Python, instead one should use None and then maybe instantiate the class within the function body.
=> Improved get_envelope by adding exn/eyn and remove mutable kwarg.

ocelot/gui/accelerator.py
I fixed some of the labels and whatnot in compare_beams and show_e_beam so the resulting plots looks nicer and are more consistent.
=> better typesetting of labels for show_e_beam and compare_beams

ocelot/gui/accelerator.py
i made a mistake in the previous merge where the xlabel units were wrong, they were mm but they should be um.  you can tell they should be um by the 1e6 multiplicative factor in some of the plots.  it's fixed in this pull request
=> wrong xlabel, should be um not mm

ocelot/adaptors/tfs.py, unit_tests/adaptors_test/test_tfs.py
Now fails gracefully if the optional dependency (tfs-pandas) is missing.  Also delete dead code that should never be used. Add friendly warning if the tfs-pandas module is missing and the user tries to import the tfs adaptor.  The TFS adaptor tests are skipped if the optional package is missing.
=> fix tfs adaptor regarding its tests

ocelot/cpbd/beam.py, ocelot/cpbd/optics.py, ocelot/cpbd/track.py, unit_tests/cpbd/test_beam.py
track and twiss returning an iterable of Twiss instances can be difficult and unwieldy.  Having to do list
comprehensions to look at any variable is annoying.  To manipulate the data will then
also require a conversion to a np.array.  Far easier to just use a Pandas DataFrame.  I
also include a method for converting a Twiss instance to a Pandas Series.  The kwarg
return_df are for the two functions track and twiss.
=> Options to return pd.DataFrame instead of list of Twiss instances

ocelot/cpbd/csr.py
matplotlib.pyplot is a module.  Modules cannot be picked.  This means instances of
the class cannot be deepcopied (or for example used in multiprocessing...), so best
really to not do this.  This leads to crashes in for example
Navigator.add_physics_proc when you have added CSR with pict_debug enabled to the
Navigator.  In essence this meakes pict_debug unusable.
=> Fix bug caused by having matplotlib as a CSR instance attribute

ocelot/adaptors/pmd.py
fix sign convention in z.  +ve is in front of reference in pmd, but -ve in ocelot.
=> openpmd loader bug fix

ocelot/cpbd/csr.py
delete unnecessary printout on every step.  only print warnings when needed.
=> silence printout in SaferCSR class

ocelot/cpbd/beam.py
On the off chance the macro particle charges are different!  Otherwise this will be wrong...
=> In ParticleArray.sort(in_place=True): also sort the q_array

ocelot/__init__.py, ocelot/cpbd/elements/__init__.py, ocelot/cpbd/elements/sequence.py
Just pollutes the namespace, has no functionality as far as I can tell, so slows down import for example.  Also clashes with `typing.Sequence` in Python standard library package `typing`, which is annoying.
=> Delete class Sequence and module sequence that does nothing.

ocelot/cpbd/magnetic_lattice.py
i made the flatten function more readable and better etc a long time ago, it works for any non-infinitely nested iterable (e.g. not strings..)  and not just list/tuple like previous implementation.
=> more readable and better flatten function.

ocelot/cpbd/magnetic_lattice.py
tests pass.  still failing tests but they failed before the flatten function and i think are specific somehow to my platform.  
with this commit:
before bad flatten function was introduced (tested with ef58a270)
=> if non iterable is passed to flatten function, then just yield it.

ocelot/cpbd/csr.py
Can't happen in the init as the init doesn't actually intialise, it is set
manually.  So has to happen in prepare.
If a user thinks: "ok I would like to use `rk_traj` in `CSR`", they may easily forget to also set `energy`.  If they don't set it, they simply get incorrect results, but no explanation why.  This is why.  It is never correct to set `rk_traj` without also `energy`, so raise an exception.
=> Raise when rk_traj is selected but without an energy in CSR.prepare

ocelot/adaptors/wake_t.py
This PR updates the Wake-T adaptor so that it works with the latest [0.5.0](https://github.com/AngelFP/Wake-T/releases/tag/v0.5.0) release.
=> Update Wake-T adaptor

ocelot/adaptors/genesis.py
The default version of Genesis 1.3 (version 2) available on the Maxwell cluster (module load genesis/2.0) has problems reading the beam files generated by the genesis2 adaptor and crashes. Weilun suggested to limit the size of the ASCII floats that are written to 8 decimals. Indeed this solved the error.
I have not tested whether the same change is necessary in the radiation file (see line 3160).
=> limit size of ASCII floating numbers in genesis beam input file

ocelot/cpbd/csr.py
Some branches of calculating (w, Ks) return Ks as a float, and others return it as an array. This crashes the program when Ks is a float. Here is my suggestion to fix it.
=> bugfix KS with wrong shape

ocelot/cpbd/io.py, unit_tests/cpbd/test_io.py, unit_tests/cpbd/test_track.py
this saves crashes and failed tests when this optional dependency isn't installed
=> skip tests and class defn when h5py is not installed

ocelot/adaptors/genesis4.py
Solve issue in functions `populate_sequence_beam_array` and `populate_sequence_beam` caused by absence of 'time' element in sequence. This is for instance relevant when setting up steady-state simulations.
=> g4adaptor: bugfix for steady-state simulations

ocelot/adaptors/openpmd.py, unit_tests/adaptors_test/test_openpmd.py
This module contains methods for reading/writing in openpmd format.
Adapted for Ocelot from APTools: https://github.com/AngelFP/APtools/blob/master/aptools/data_handling/saving.py
@authors: A. Ferran Pousa, A. Martinez de la Ossa.
This module provides the class `SaveBeamOPMD` (derived from `PhysProc`) to enable automatic beam savings at or between the given `Markers`.
The writing period can be adjusted independently using the parameter `step` in  `SaveBeamOPMD`.
=> Add adaptor for openPMD data

ocelot/gui/genesis4_plot.py
Currently this is implemented for the plot panel generated by function `subfig_z_energy_espread_bunching`. 
Typical use case:
```
gout = read_gout4('./simout/demo.out.h5’)
gout.x_Icutoff=100
plot_gen4_out_z(gout, z=gout.z[-1], showfig=True, savefig=False)
```
If the propery `x_Icutoff` of Genesis4Output instance returned by `read_gout4` is not set, the behavior of the plotting code is unchanged.
The advantage becomes visible when plotting results of one4one simulations with small currents on the margins of the bunch. In the screenshot on the left (test simulation with one4one=1), slices with current=0A are plotted with zero avg. energy (note the range of the vertical energy axis). In the plot on the right these slices are ignored and one can see the energy (spread) profile along the …
=> current cut-off in G4 plots

ocelot/utils/git_commit_id.py
This function allows to obtain the git commit id of the active OCELOT installation (= the installation that was loaded by the Python interpreter). This is useful for OCELOT developers and users who want to keep track of the version used to prepare a simulation.
Example copied from the code in this pull request:
```
>>> from ocelot.utils.git_commit_id import get_git_commit_id
>>> x=get_git_commit_id()
>>> print(x)
16425bd808d2c45e62d512093ee51190969fa5d7
```
=> function to obtain git commit id of OCELOT installation

ocelot/utils/xfel_utils.py
- `create_fel_beamline`: added optional parameter to adjust number of lattice cells in returned lattice (if parameter is not provided the result remains unchanged)
- bugfixes in `create_fel_lattice`: check of intersection length; fix issue resulting in the number of undulators in generated beamline to be always odd
=> EuXFEL lattice generation functions: improvements/bugfixes

demos/fel/demo_lat_matchN2.py, ocelot/utils/xfel_utils.py, unit_tests/utils_test/xfel_utils_test.py
Introduces new parameter `final_halfcell_complete` to functions `create_fel_beamline` and `create_fel_lattice`. If True, all generated half-cells are identical, allowing matching of FODO lattice even for beamlines with just `und_N=2` undulators. The default value is False, so unless specified the behavior of the functions remains unchanged.
Fixed remaining issue in function `create_fel_lattice` related to parameter `und_N`, not in all cases the requested number of undulators was returned.
Includes a demo script matching an undulator lattice with just two undulators. After matching the resulting beta functions are displayed.
=> EuXFEL lattice generation functions: improvements/bugfixes 2

demos/fel/demo_lat_callback.py, ocelot/adaptors/genesis4.py
Add support for callback functions to the lattice writing code in OCELOT adaptor for "GENESIS 1.3", v4.
If provided when calling the function `write_gen4_lat`, the callback function gets called for every lattice element while writing a lattice file. This enables the user to override the default behavior and manipulate/replace what is written to the file. As demonstrated by the included demo, one use case is to support new (developer) features of "GENESIS 1.3", v4 without having to modify the adaptor code.
Also reorganized the lattice file generation code in the adaptor.
The included demo script generates a short SASE1-type undulator beamline and matches periodic FODO solution. Then the lattice is written twice:
(i) with standard behavior (not using a callback function); and
(ii) …
=> callback functionality for lattice writing code (adaptor for "GENESIS 1.3", v4)

ocelot/adaptors/genesis.py, unit_tests/adaptors_test/test_g4adaptor.py
Description:
* Implements tests for callback functionality recently added to write_gen4_lat function in adaptor for GENESIS 1.3, v4.
* Disabled broken test function `test_beam_transform` in adaptor for GENESIS 1.3, v2 (file `ocelot/adaptors/genesis.py`).
Note that currently the test triggers about 30 warnings of type PendingDeprecationWarning resulting from use of the deprecated numpy.matrix in the `genesis.py`. To fix these, changes to genesis.py will be needed.
=> test for callbacks from write_gen4_lat (adaptor for GENESIS 1.3, v4)

ocelot/adaptors/genesis4.py
The current implementation of function clean_output can result in undesired side-effects, i.e. in certain scenarios it could delete more files than intended. Adds TODO to the function.
=> adaptor for GENESIS 1.3, v4: add TODO to function clean_output

ocelot/rad/fel.py, unit_tests/rad_test/fel_mx.py
In ocelot/rad/fel.py there was a disabled test case, move it to dedicated pytest test.
Compares result of OCELOT Ming Xie estimator against example given in
M. Xie, "Exact and variational solutions of 3D eigenmodes in high gain FELs", Nucl. Instruments Methods Phys. Res. Sect. A Accel. Spectrometers, Detect. Assoc. Equip., vol. 445, no. 1--3, pp. 59--66, 2000; DOI https://doi.org/10.1016/S0168-9002(00)00114-5
=> pytest test fixture for Ming Xie estimator

ocelot/rad/fel.py
Correction/bug fix for MX estimation in the case of harmonic lasing.
Verified that lg3 and rho3 for Ming Xie estimations at fundamental (h=1) are unchanged, this was tested with the new version of `unit_tests/rad_test/fel_mx.py` in commit id a938bd3 .
In this version, the MX estimation (for h>1, h odd) of some parameters still needs to be implemented, info messages are displayed.
=> MX estimation for harmonic lasing

ocelot/common/math_op.py, ocelot/cpbd/beam_params.py, ocelot/cpbd/chromaticity.py, ocelot/cpbd/csr.py, ocelot/cpbd/reswake.py, ocelot/rad/radiation_py.py, ocelot/utils/acc_utils.py
Fixes #255 
Replace the deprecated functions `simps` and `cumtrapz` since the latest scipy v1.14.0 release with `simpson` and `cumulative_trapezoid`
=> Replace deprecated functions in scipy v1.14.0

setup.py
dependent packages can will now be able to use ocelot's type hints
https://peps.python.org/pep-0561/
=> Enable OCELOT's type hints for downstream packages that use OCELOT

ocelot/cpbd/track.py, unit_tests/cpbd/test_get_envelope.py
By default, Ocelot uses a certain function called `get_envelope` to calculate the Twiss parameters of the beam being tracked by the `track` function.
This PR allows the users to pass their own `get_twiss` function to `track` to achieve this task.
Usage:
```py
tws_track, _ = track(lat, parray, navi, get_twiss=get_envelope_custom)
```
where `get_envelope_custom` is the function that the user defines, which receives at least a `ParticleArray` object as argument, e.g.:
```py
def get_envelope_custom(p_array, **kwargs):
...
return tws
```
Note that the `**kwargs` is needed in order to absorb any arguments passed to the function inside `track`, which are not used by the custom function.
This is an example of a custom function that accounts for the weights of individual particles in the …
=> Allow the user to pass a custom `get_twiss` function to `track`
