ocelot/gui/genesis_plot.py, ocelot/optics/wave.py
add methods proj() and slice_2d() in StokesParameters()
some improvements in plot_stokes_3d()
=> Improvements in/for plot_stokes_3d()

demos/stokes_parameters/plot_stokes_3d.py, ocelot/gui/genesis_plot.py, ocelot/optics/wave.py
added colorbars in plot_stokes_3d() (unfinished)
reorganized plotting and intersecting in plot_stokes_3d()
some bug fixed in StokesParameters()
=> reorganized plotting in plot_stokes_3d()

ocelot/adaptors/genesis4.py
writes RadiationField object to Genesis1.3 v4 radiation file
=> Added write_dfl4() func to ocelot/adaptors/genesis4.py

demos_tests/wave_test/generate_gaussian_dfl/generate_gaussian_dfl_test.py, ocelot/adaptors/genesis4.py
Change f-strings to format output in write_dfl4() and generate_gaussian_dfl_test.py
=> Change f-strings to format output

ocelot/optics/wave.py
add circle and square aperture, modify prop m
=> aperture and prop_m modification

ocelot/cpbd/elements.py
I propose to add __str__ methodes to elements (and maybe many other objects) so that a print() gives some meaningful result and not just a pointer to the object.
=> bug fix for bends in survey

ocelot/cpbd/beam.py, ocelot/cpbd/physics_proc.py, unit_tests/utils_test/particle_array_test.py
This change adds functionality to save the indices of particles that are getting lost by physics processes e.g. apertures.
=> Tracking lost particles in ParticleArray

demos/other/beam2edist2beam.py, ocelot/adaptors/genesis.py
add correct dg generator, checked Twiss parameters and add to demos non-zero alpha, and quadratic chirps to beta, emit, and dg to test beam to edist function
=> Fix dg bag, checked cov matrix

ocelot/cpbd/physics_proc.py
Added EllipticalAperture directly instead of the circular aperture we talked about in the control room.
=> added EllipticalAperture

ocelot/utils/T_run_demo.sh, ocelot/utils/T_run_g2.sh, ocelot/utils/demo_MpiQueueLauncher.py, ocelot/utils/launcher.py
Hi Svitozar,
I've pushed the initial version of MpiQueueLauncher.
There is Python demo script "demo_MpiQueueLauncher.py" that can be run after git checkout directly in its directory (a few files are written to that directory in the process). It demonstrates several ways to launch/manage jobs and generates several cluster jobs that run for 60 seconds each.
I am available for discussions if needed.
Best
Christoph
=> mpiqueuelauncher: initial version

unit_tests/adaptors_test/test_pmd.py
Ignore pmd tests when pmd isn't installed.
=> bugfix: Missing import pmd

ocelot/adaptors/genesis.py
Enables GENESIS2 experts to insert text into G2 infiles.
=> Cl 20210209  g2adaptor expertinput

demos/optics/demo_ap_rect_apscan.py, ocelot/optics/wave.py
=> wave.py: scan of rect. aperture and compute resulting energies

ocelot/cpbd/tm_utils.py
It is supposed to be optional.
=> Fix numba being a mandatory dependency.

ocelot/cpbd/beam.py, unit_tests/cpbd/test_beam.py
I added a property for getting the total charge of a ParticleArray instance.  + a test.
=> total charge property on ParticleArray.

ocelot/adaptors/mad8.py
This is an adaptor for converting MAD8 twiss output to an ocelot lattice + initial beam optics.  Previous one I could not get to work, but this one works.  E.g. it used below in section of xfel for conversion showing perfect agreement.
=> MAD8 Twiss adaptor

ocelot/adaptors/wake_t.py
Wake-T has had some recent changes that make it necessary to update the adaptors. When making this update, I also added type hints to the methods, so that IDEs can better keep track of what comes in and out.
=> Update Wake-T adaptor

ocelot/optics/wave.py
added a few info comments to wave.py
=> info comments

ocelot/cpbd/match.py, ocelot/cpbd/navi.py
=> unit_step Navigator kwarg and match_beam print output

unit_tests/ebeam_test/section_track/accelerator/s2e_sections/sections.py, unit_tests/ebeam_test/wake/wake_test.py
=> fix wake paths in sections tests

CHANGELOG.md, ocelot/cpbd/csr.py, ocelot/cpbd/physics_proc.py, ocelot/cpbd/sc.py, ocelot/cpbd/wake3D.py
now easier to see how the processes are configured and can see what is going on.  useful for debugging/diagnostics
Update CHANGELOG.md
=> added __repr__ to common physics processes

demos/optics/8-prop_iris_line.py, ocelot/optics/wave.py
loss_per_cell_array cannot be deduced from rad_left_array as it's calculated in fractions. Otherwise need to return absolute values and each time recalculate fractions for loss_per_cell_array and rad_left_array outsize of dfl_prop_iris
=> fixes to pull request #195

ocelot/adaptors/genesis4.py
Adds feature to function `write_gen4_lat` to write a user-provided string to the generated lattice file.
=> direct writing of string to lattice file (adaptor for GENESIS 1.3, v4)

unit_tests/adaptors_test/test_g4adaptor.py
- added test for code writing user-defined strings directly into lattice file
- put code generating test lattice into own function
=> more tests for genesis4 adaptor lattice functions

unit_tests/rad_test/fel_mx.py
check lg3 and rho3 against numerical values computed with code version eb3fbdf.
=> more MX testing
